/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Fragment;

/**
 *
 * @author Admin
 */
public class LowLevelP extends javax.swing.JPanel {

    /**
     * Creates new form LowLevelP
     */
    public LowLevelP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JTextField();
        footer = new javax.swing.JTextField();
        warnning = new javax.swing.JTextField();
        warnning1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));

        header.setBackground(new java.awt.Color(255, 204, 0));
        header.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
        header.setForeground(new java.awt.Color(0, 0, 0));
        header.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        header.setText("//////////////////////////////////////");
        header.setFocusable(false);
        header.setOpaque(true);

        footer.setBackground(new java.awt.Color(255, 204, 0));
        footer.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
        footer.setForeground(new java.awt.Color(0, 0, 0));
        footer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        footer.setText("///////////////////////////////////////////");
        footer.setFocusable(false);
        footer.setOpaque(true);

        warnning.setBackground(new java.awt.Color(255, 204, 0));
        warnning.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        warnning.setForeground(new java.awt.Color(0, 0, 0));
        warnning.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        warnning.setText("Your Level Are To Low ");
        warnning.setFocusable(false);
        warnning.setOpaque(true);

        warnning1.setBackground(new java.awt.Color(255, 204, 0));
        warnning1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        warnning1.setForeground(new java.awt.Color(0, 0, 0));
        warnning1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        warnning1.setText("To Access this Feture");
        warnning1.setFocusable(false);
        warnning1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(warnning)
            .addComponent(warnning1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(warnning, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warnning1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField footer;
    private javax.swing.JTextField header;
    private javax.swing.JTextField warnning;
    private javax.swing.JTextField warnning1;
    // End of variables declaration//GEN-END:variables
}
