/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Fragment;

import Tools.Pair;

/**
 *
 * @author Admin
 */
public class ProdField extends javax.swing.JPanel {

    /**
     * Creates new form ExtraProdFieldP
     */
    public ProdField() {
        initComponents();
    }
    public ProdField(String field, String des) {
        initComponents();
        setField(field);
        setDescription(des);
    }
    
    //
    public void setField(String field){
        fieldLabel.setText(field);
    }
    public String getField(){
        return fieldLabel.getText();
    }
    
    public void setDescription(String des){
        desTxt.setText(des);
    }
    public String getDescription(){
        return desTxt.getText();
    }
    public void setEditable(boolean c){
        desTxt.setEditable(c);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldLabel = new javax.swing.JLabel();
        desTxt = new javax.swing.JTextField();

        fieldLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fieldLabel.setText("Field");

        desTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        desTxt.setText("description");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desTxt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField desTxt;
    private javax.swing.JLabel fieldLabel;
    // End of variables declaration//GEN-END:variables
}
