/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Fragment;

import DTO.SectionDTO;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class SectionP extends javax.swing.JPanel {
    private SectionDTO sect;
    private boolean isSelected, isIn;
    private Color oldc;
    private final int imgsz = 130;
    /**
     * Creates new form SectionP
     */
    public SectionP(SectionDTO sect) {
        initComponents();
        this.sect = sect;
        this.isSelected = false;
        this.isIn = false;
        this.oldc = this.getBackground();
        setData();
    }
    
    private void setData(){
        ImageIcon mg = new ImageIcon(sect.getImageDIR());
        Image a = mg.getImage().getScaledInstance(imgsz, imgsz, Image.SCALE_SMOOTH);
        mg = new ImageIcon(a);
        img.setIcon(mg);
        
        code.setText(sect.getCode());
        sizeFreeOutOf.setText(sizeFreeOutOf.getText().replaceAll("-1-", sect.getFree().toString())
                                                        .replaceAll("-2-", sect.getSize().toString()));
        totalV.setText(sect.getValue().toString());
        if(this.sect.getFree() <= this.sect.getSize()/20){
            this.oldc = Color.RED;
            this.setBackground(oldc);
        }
    }
    
    public SectionDTO getData(){
        return this.sect;
    }
    
    public boolean isSelect(){
        return this.isSelected;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        code = new javax.swing.JLabel();
        sizeFreeOutOf = new javax.swing.JLabel();
        totalVLb = new javax.swing.JLabel();
        totalV = new javax.swing.JLabel();
        spacePB = new javax.swing.JProgressBar();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        img.setBackground(new java.awt.Color(102, 102, 102));
        img.setOpaque(true);

        lb1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb1.setText("Section code :");

        code.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        code.setText("---");

        sizeFreeOutOf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sizeFreeOutOf.setText("|-1-|   Free out of :   |-2-|");

        totalVLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalVLb.setText("Total value :");

        totalV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalV.setText("---");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sizeFreeOutOf, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(spacePB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(totalVLb)
                        .addGap(18, 18, 18)
                        .addComponent(totalV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(code, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb1)
                    .addComponent(code))
                .addGap(18, 18, 18)
                .addComponent(spacePB, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sizeFreeOutOf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalVLb)
                    .addComponent(totalV)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.isIn = true;
    }//GEN-LAST:event_formMouseEntered

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if(this.isIn){
            this.isSelected = !this.isSelected;
            if(this.isSelected){
                this.setBackground(Color.ORANGE);
            }else{
                this.setBackground(oldc);
            }
        }
    }//GEN-LAST:event_formMouseClicked

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.isIn = false;
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel code;
    private javax.swing.JLabel img;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel sizeFreeOutOf;
    private javax.swing.JProgressBar spacePB;
    private javax.swing.JLabel totalV;
    private javax.swing.JLabel totalVLb;
    // End of variables declaration//GEN-END:variables
}
