package UI.Login;

import User.HashPassword;
import User.User;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lambo
 */
public class signup_form extends javax.swing.JFrame {

    /**
     * Creates new form sign up_form
     */
    public signup_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Staff_ID = new javax.swing.JTextField();
        ChoosePassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ConfirmPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        condition4 = new javax.swing.JLabel();
        condition1 = new javax.swing.JLabel();
        condition2 = new javax.swing.JLabel();
        condition3 = new javax.swing.JLabel();
        condition5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setText("Sign-up");

        jLabel2.setText("Choose Password:");

        jLabel3.setText("Staff ID:");

        jLabel4.setText("Confirm Password:");

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        condition4.setForeground(new java.awt.Color(255, 0, 0));

        condition1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        condition1.setText("- Staff ID must follows form \"SMempl***\" with *** as numbers.");

        condition2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        condition2.setText("- Password's length must not be under 8 characters.");

        condition3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        condition3.setText("- Password only contains numbers, uppercase and lowercase letters.");

        condition5.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(Staff_ID)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChoosePassword)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmPassword)
                    .addComponent(condition4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(condition1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(condition2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(condition3, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(condition5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Staff_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(condition5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChoosePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(condition4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(condition1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(condition2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(condition3)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        var username = Staff_ID.getText();
        var password1 = ChoosePassword.getText();
        var password2 = ConfirmPassword.getText();

        boolean cdt1 = isValidUsername(username);
        boolean cdt2 = isPasswordLengthValid(password1);
        boolean cdt3 = isCharacterValidPassword(password1);
        boolean cdt4 = arePasswordsMatching(password1, password2);

        if(!cdt1) condition1.setForeground(Color.red);
        else condition1.setForeground(new Color(50,133,37));

        if(!cdt2) condition2.setForeground(Color.red);
        else condition2.setForeground(new Color(50,133,37));

        if(!cdt3) condition3.setForeground(Color.red);
        else condition3.setForeground(new Color(50,133,37));

        if(!cdt4)
        {
            condition4.setText("Confirming password mismatched.");
        }
        else condition4.setText("");

        if(cdt1 && cdt2 && cdt3 && cdt4)
        {
            try {
                User newUser = new User(username, new HashPassword().hashPassword(password1));
                if(newUser.addUser()){
                    JOptionPane.showMessageDialog(null, "Your sign-up request has been sent to administrator. Awaiting for approval.");
                }
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(signup_form.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed
    private static boolean isValidUsername(String username) {
        // Định dạng regex cho username là "SMempl" và 3 chữ số
        String regex = "^SMempl\\d{3}$";

        // Biên dịch regex thành Pattern
        Pattern pattern = Pattern.compile(regex);

        // Tạo một matcher để so khớp với username
        Matcher matcher = pattern.matcher(username);

        // Kiểm tra xem username có khớp với regex không
        return matcher.matches();
    }
    
    private static boolean isPasswordLengthValid(String password) {
        // Kiểm tra xem chiều dài mật khẩu có lớn hơn hoặc bằng 8 không
        return password.length() >= 8;
    }
    
    // Hàm kiểm tra mật khẩu
    private static boolean isCharacterValidPassword(String password) {
        // Kiểm tra xem mật khẩu chỉ chứa chữ cái in hoa, chữ cái in thường và số
        return password.matches("^[a-zA-Z0-9]+$");
    }
    
    private static boolean arePasswordsMatching(String password1, String password2) {
        return password1.equals(password2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ChoosePassword;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JTextField Staff_ID;
    private javax.swing.JLabel condition1;
    private javax.swing.JLabel condition2;
    private javax.swing.JLabel condition3;
    private javax.swing.JLabel condition4;
    private javax.swing.JLabel condition5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
