/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author Admin
 */
import DAO.ProductDAO;
import DAO.SectionDAO;
import javax.swing.table.DefaultTableModel;
import javax.swing.ListSelectionModel;


public class ProductListPane extends javax.swing.JPanel {
    ProductDAO p = new ProductDAO();
    DefaultTableModel model1 = new DefaultTableModel(
            new Object[][] {
                { "11", "12", "13", "14" }, 
                { "21", "22", "23", "24" },
                { "31", "32", "33", "34" }, 
                { "41", "42", "44", "44" }},
            new Object[] { "A", "B", "C", "D" }
        );
    DefaultTableModel model = new DefaultTableModel(
            new Object[][] {
                { "some", "text" }, 
                { "any", "text" }, 
                { "even", "more" },
                { "text", "strings" }, 
                { "and", "other" }, 
                { "text", "values" } },
      new Object[] { "Column 1", "Column 2" });
    /**
     * Creates new form ProductsListPane
     */
    public ProductListPane() {
        initComponents();
        try{
            productList.setModel(fixedJTable.fixed(p.listOfProduct()));
        }catch(Exception e){}
    }
    
    //Method for selected product
    public String selectedProd(){
        String res = productList.getValueAt( productList.getSelectedRow(),0).toString();
        return res;
    }
    //method to override
    public void editPanelJumper(){
        // jum to EditPanel
//        productList.setModel(new DefaultTableModel());
    }
    public void backOverride(){
        //to be override;
    }
    
    //to to in
    public void sortBoxSelectEvent(){
        try {
            String types = sortByBox.getSelectedItem().toString();
            productList.setModel(p.sortProductBy(types));
        } catch (Exception e) {
        }
        
    }
    public void sample1(){
        String sortType = "";
        sortType = sortByBox.getItemAt(sortByBox.getSelectedIndex()).toLowerCase();
        listName.setText("Product List sorted by " + sortType );
        
        DefaultTableModel sorted;
        // DAO get DefaultTableModel sorted 
//        sorted = DAO;
        sorted = fixedJTable.fixed(model1);
        productList.setModel(sorted);
    }
    
    public void sample2(){
        listName.setText("Product List");
        DefaultTableModel defl;
        // DAO get DefaultTableModel defl;
        defl = fixedJTable.fixed(model);
        productList.setModel(defl);
    }
    
    public void sample3(){
        ProductDAO p = new ProductDAO();
        try{
            productList.setModel(p.listOfProduct());
        }catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productList = new javax.swing.JTable();
        listName = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        editButon = new javax.swing.JButton();
        sortByBox = new javax.swing.JComboBox<>();
        backButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        productList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        productList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        productList.setRowSelectionAllowed(true);
        jScrollPane1.setViewportView(productList);

        listName.setText("Product List");

        refreshButton.setText("REFRESH");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        editButon.setText("EDIT");
        editButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButonActionPerformed(evt);
            }
        });

        sortByBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sortByBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Code", "Name", "Brand", "Quantity", "Space", "Price" }));
        sortByBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByBoxActionPerformed(evt);
            }
        });

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listName, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sortByBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(editButon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(97, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton)
                    .addComponent(backButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sortByBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editButon)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        sample2();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void editButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButonActionPerformed
        editPanelJumper();
    }//GEN-LAST:event_editButonActionPerformed

    private void sortByBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByBoxActionPerformed
        sortBoxSelectEvent();
    }//GEN-LAST:event_sortByBoxActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        backOverride();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton editButon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel listName;
    private javax.swing.JTable productList;
    private javax.swing.JButton refreshButton;
    private javax.swing.JComboBox<String> sortByBox;
    // End of variables declaration//GEN-END:variables
}
