/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Base;

import Controler.MainControler;
import UI.Fragment.LowLevelP;
import UI.Popup.PopupMenuP;
import User.User;
import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import java.awt.CardLayout;
import java.awt.event.MouseEvent;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author Admin
 */
public class NavBoard extends javax.swing.JFrame {
    CardLayout layout;
    PopupMenuP popmenu;
    JPanel displayer;
    private MainControler mc;
    int nowM;
    /**
     * Creates new form DashBoard
     * @param mc
     */
    public NavBoard( MainControler mc) {
        initComponents();
        this.mc = mc;
        
        this.setTitle("Inventory Manager 2.0");
        layout = new CardLayout();
        nowM = 0;
        popmenu = new PopupMenuP(){
            @Override
            public void doIt(){
                topCard(getNowP());
            }
            @Override
            public void mouseExited(MouseEvent evt){
                if(nowM > 0 && evt.getX() > popmenu.sizE ){
                    popMenuSH();
                }
            }
            
        };
        displayer = new JPanel();
        // Initiate
        UserPanel up = new UserPanel(this.mc);
        ProductListPanel plp = new ProductListPanel(this.mc);
        SectionListPanel slp = new SectionListPanel(this.mc);
        ImportPanel ip = new ImportPanel();
        LogPanel lp = new LogPanel(this.mc);
        
        //displayer
        displayer.setLayout(layout);
        displayer.add(popmenu.getUserButName(), up);
        displayer.add(popmenu.getProdButName(),plp);
        displayer.add(popmenu.getSectButName(),slp);
        if(this.mc.getUser().getLevel() > 9){
            displayer.add(popmenu.getImpoButName(),ip);
        }else{
            displayer.add(popmenu.getImpoButName(),new LowLevelP());
        }
        if(this.mc.getUser().getLevel() > 9){
            displayer.add(popmenu.getLogButName(),lp);
        }else{
            displayer.add(popmenu.getLogButName(),new LowLevelP());
        }
        
        
        //reposition
        displayPanel.add(popmenu, JLayeredPane.POPUP_LAYER);
        displayPanel.setLayer(popmenu, nowM);
        displayPanel.add(displayer, JLayeredPane.DEFAULT_LAYER);
        displayPanel.setLayer(displayer, 1);
        

    }
    //Override importer
    public void topCard(String displaying){
        layout.show(displayer, displaying);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //Action Performed Method
    public void resized(){
        popmenu.setBounds(0, 0, popmenu.sizE, displayPanel.getHeight());
        displayer.setBounds(0, 0, displayPanel.getWidth(), displayPanel.getHeight());
    }
    public void menuEntered(){
        if(nowM == 0){
            popMenuSH();
        }
    }
    public void popMenuSH(){
        nowM++;
        if(nowM%2==0){
            nowM = 0;
        }else{
            nowM = 5;
        }
        displayPanel.setLayer(popmenu, nowM);
    }

    //
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayPanel = new javax.swing.JLayeredPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                displayPanelComponentResized(evt);
            }
        });

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        jMenuBar1.setOpaque(true);

        menuMenu.setBackground(new java.awt.Color(255, 102, 51));
        menuMenu.setForeground(new java.awt.Color(0, 0, 0));
        menuMenu.setText("MENU");
        menuMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuMenu.setOpaque(true);
        menuMenu.setPreferredSize(new java.awt.Dimension(70, 22));
        menuMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMenuMouseEntered(evt);
            }
        });
        jMenuBar1.add(menuMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayPanel)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMenuMouseClicked
        popMenuSH();
    }//GEN-LAST:event_menuMenuMouseClicked

    private void displayPanelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_displayPanelComponentResized
        resized();
    }//GEN-LAST:event_displayPanelComponentResized

    private void menuMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMenuMouseEntered
        menuEntered();
    }//GEN-LAST:event_menuMenuMouseEntered

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        try{
//            UIManager.setLookAndFeel(new FlatArcOrangeIJTheme());
//        }catch(Exception e){
//            e.printStackTrace();
//        }
//
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                User u = new User("Admin", "a1920e3f3ea027f7248b0dc5a9bb8b7525269c4e1b3ce5acddddddb68d23c95e");
//                u.getUser();
//                MainControler mc =new MainControler(u);
//                new NavBoard(mc).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane displayPanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuMenu;
    // End of variables declaration//GEN-END:variables
}
