/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Base;

import Controler.MainControler;
import UI.Fragment.OtherUserP;
import User.HashPassword;
import User.User;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.File;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class UserPanel extends javax.swing.JPanel {
    final JFileChooser imgChoser = new JFileChooser();    
    private MainControler mc;
    private User user;
    private int imgsz = 200;
    private int mode = 0;
    /**
     * Creates new form UsrePanel
     */
    public UserPanel(MainControler mc) {
        initComponents();
        this.mc = mc;
        this.user = mc.getUser();
        setData();
        setMode();
        setOther();
    }
    
    private void setOther(){
        otherUser.removeAll();
        for(User u : user.allUser()){
            otherUser.add(new OtherUserP(this.user, u){
                @Override
                public void removeMe(){
                    setOther();
                }
            });
        }
        int r = user.allUser().size();
        r = r/2 + r%2;
        otherUser.setLayout(new GridLayout(r,2));
    }

    
    private void setData(){
        name.setText(user.getName());
        
        lvl.setText(user.getLevel() + "");
        dateOfB.setText(user.getDateOfBirth());
        userName.setText(user.getUsername());
        if(user.getGender()!= null){
            genderCB.setSelectedItem(user.getGender());
        }else{
            genderCB.setSelectedItem(0);
        }
        ImageIcon mg = new ImageIcon(user.getImageDIR());
        Image a = mg.getImage().getScaledInstance(imgsz, imgsz, Image.SCALE_SMOOTH);
        mg = new ImageIcon(a);
        img.setIcon(mg);
    }
    
    private void setMode(){
        name.setEnabled(mode == 1);
        dateOfB.setEnabled(mode == 1);
        userName.setEditable(false);
        genderCB.setEnabled(mode == 1);
        saveBt.setVisible(mode == 1);
        imgBt.setVisible(mode == 1);
        EditBt.setVisible(mode != 1);
        
    }
    
    private void getData(){
        User nu = new User(user.getUsername(), user.getPassword());
        if(nu.getUser()){
            nu.setName(name.getText());
            nu.setGender(genderCB.getSelectedItem().toString());
            nu.setDateOfBirth(dateOfB.getText());
            nu.setImageDIR(user.getImageDIR().replaceAll("\\\\", "\\\\\\\\"));
            user.updateInfo(nu);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userInfo = new javax.swing.JPanel();
        ulb1 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        lb2 = new javax.swing.JLabel();
        lvl = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        lb3 = new javax.swing.JLabel();
        dateOfB = new javax.swing.JTextField();
        resetPassBt = new javax.swing.JButton();
        EditBt = new javax.swing.JButton();
        saveBt = new javax.swing.JButton();
        imgBt = new javax.swing.JButton();
        lb5 = new javax.swing.JLabel();
        genderCB = new javax.swing.JComboBox<>();
        allUserSroll = new javax.swing.JScrollPane();
        otherUser = new javax.swing.JPanel();

        ulb1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ulb1.setText("User Info");

        lb1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb1.setText("Name :");

        img.setBackground(new java.awt.Color(0, 153, 153));
        img.setOpaque(true);

        name.setText("nnn");

        lb2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb2.setText("Level :");

        lvl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lvl.setText("0");

        lb4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb4.setText("Username :");

        userName.setText("nnn");

        lb3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb3.setText("Date of Birth :");

        dateOfB.setText("nnn");

        resetPassBt.setText("Reset Password");
        resetPassBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPassBtActionPerformed(evt);
            }
        });

        EditBt.setText("Edit");
        EditBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtActionPerformed(evt);
            }
        });

        saveBt.setText("Save");
        saveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtActionPerformed(evt);
            }
        });

        imgBt.setText("Browse Image");
        imgBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgBtActionPerformed(evt);
            }
        });

        lb5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb5.setText("Gender :");

        genderCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Croissant", "Male", "Female" }));

        javax.swing.GroupLayout userInfoLayout = new javax.swing.GroupLayout(userInfo);
        userInfo.setLayout(userInfoLayout);
        userInfoLayout.setHorizontalGroup(
            userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoLayout.createSequentialGroup()
                .addGroup(userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ulb1)
                    .addGroup(userInfoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb5)
                            .addComponent(lb3)
                            .addComponent(lb2)
                            .addComponent(lb1)
                            .addComponent(lb4))
                        .addGap(18, 18, 18)
                        .addGroup(userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lvl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                            .addComponent(genderCB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateOfB))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(imgBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetPassBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        userInfoLayout.setVerticalGroup(
            userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoLayout.createSequentialGroup()
                .addGroup(userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(userInfoLayout.createSequentialGroup()
                        .addComponent(ulb1)
                        .addGap(18, 18, 18)
                        .addGroup(userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userInfoLayout.createSequentialGroup()
                                .addGroup(userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb4))
                                .addGap(18, 18, 18)
                                .addGroup(userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb1)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb2)
                                    .addComponent(lvl))
                                .addGap(18, 18, 18)
                                .addGroup(userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb3)
                                    .addComponent(dateOfB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(userInfoLayout.createSequentialGroup()
                                .addComponent(saveBt)
                                .addGap(18, 18, 18)
                                .addComponent(imgBt)
                                .addGap(18, 18, 18)
                                .addComponent(EditBt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resetPassBt))))
                    .addGroup(userInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(userInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb5)
                    .addComponent(genderCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout otherUserLayout = new javax.swing.GroupLayout(otherUser);
        otherUser.setLayout(otherUserLayout);
        otherUserLayout.setHorizontalGroup(
            otherUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1084, Short.MAX_VALUE)
        );
        otherUserLayout.setVerticalGroup(
            otherUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        allUserSroll.setViewportView(otherUser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(allUserSroll)
                    .addComponent(userInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(allUserSroll)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EditBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtActionPerformed
        this.mode = 1;
        setMode();
    }//GEN-LAST:event_EditBtActionPerformed

    private void saveBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtActionPerformed
        getData();
        this.mode = 0;
        setMode();
    }//GEN-LAST:event_saveBtActionPerformed

    private void resetPassBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPassBtActionPerformed
        try {
            String np = JOptionPane.showInputDialog("Enter new password.");
            if(np != null){
                User npu = new User(user.getUsername(), new HashPassword().hashPassword(np));
                this.user.updateInfo(npu);
                this.mode = 0;
                setData();
                setMode();
            }
        } catch (NoSuchAlgorithmException ex) {
            JOptionPane.showMessageDialog(null, "Unable to reset password");
            Logger.getLogger(UserPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_resetPassBtActionPerformed

    private void imgBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgBtActionPerformed
        int returnVal = imgChoser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION){
            File imgFile = imgChoser.getSelectedFile();
            String now = imgFile.getAbsolutePath();
            user.setImageDIR(now);
            
            ImageIcon mg = new ImageIcon(user.getImageDIR());
            Image a = mg.getImage().getScaledInstance(imgsz, imgsz, Image.SCALE_SMOOTH);
            mg = new ImageIcon(a);
            img.setIcon(mg);
        }
    }//GEN-LAST:event_imgBtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditBt;
    private javax.swing.JScrollPane allUserSroll;
    private javax.swing.JTextField dateOfB;
    private javax.swing.JComboBox<String> genderCB;
    private javax.swing.JLabel img;
    private javax.swing.JButton imgBt;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lvl;
    private javax.swing.JTextField name;
    private javax.swing.JPanel otherP;
    private javax.swing.JPanel otherP1;
    private javax.swing.JPanel otherP2;
    private javax.swing.JPanel otherP3;
    private javax.swing.JPanel otherP4;
    private javax.swing.JPanel otherUser;
    private javax.swing.JButton resetPassBt;
    private javax.swing.JButton saveBt;
    private javax.swing.JLabel ulb1;
    private javax.swing.JPanel userInfo;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
